import Head from 'next/head'
import { withRouter } from 'next/router'

const Layout = ({ router,children }) => {    
    const pathName = router.pathname
    
    return(
        <>
            <Head>
                <title>Laxmi</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/img/logo.png" />
                <link rel="stylesheet" href="/css/bootstrap.min.css" />
            </Head>
            <main className={`${pathName.includes('custom') ? 'pt-0' : ''}`}>
                {children}
            </main>
            <script src="/js/bootstrap.bundle.min.js" crossOrigin="anonymous"></script>
        </>    
    )
};

export default withRouter(Layout);
